server:
  port: 9001

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        orm:
#          jdbc:
#            bind: trace
#      springframework:
#        security: debug

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_ID}
    password: ${POSTGRES_PW}