server:
  port: 9001

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_ID}
    password: ${POSTGRES_PW}